function [mod1var, mod1varBounds, mod1Cons, mod2var, mod2varBounds, mod2Cons]= conflictPrinter(conflict,model1,model2) %,UseIndConst,IndConstrNames)
% this function prints the conflicts in a model generated by the fucntion
% conflictIdentifier. if you want to compare the conflict with a second
% model then use model2.



mod1var = model1.varNames(conflict.colind) ;
% print out conflict in seq
mod1varBounds = [model1.var_lb(conflict.colind) model1.var_ub(conflict.colind)];
mod1Cons = printConstraint(model1,   model1.constraintNames(conflict.rowind));

% print out conflict in mod
[~,b] = ismember( model1.varNames(conflict.colind),model2.varNames );
mod2var = model2.varNames(b)
mod2varBounds = [model2.var_lb(b) model2.var_ub(b)];

mod2Cons = printConstraint(model2,   model1.constraintNames(conflict.rowind));


end


